### ISSUE TITLE
No longer works

### ISSUE THREAD

**Issue by SheepCommander** [lavgup/invite-inspector#1]
Likely the "new"-ish canary update

![image](https://user-images.githubusercontent.com/66646514/149447856-6bcddb74-5223-4771-9cad-fb094ffd38ce.png)

(Note: I _am_ using better invites as well but I thought that in the past they were compatible)

**Comment by LegendModzYT** [comment]
Yeah I have the same issue, no longer works in canary. I however am not using better invites so I will install that now as invite inspector no longer works.
